#mysql:
 # build: ./mysql
# 考虑到安全问题,正式环境时不暴露端口到宿主机
 # expose:
  #    - "3306"

# 测试时使用
#  ports:
#   - 13306:3306

#my-blog:
  #image: blog/my-blog
  #ports:
   #- 28080:8080
 # links:
  # - mysql
  #此脚本于2017年8月9日再次更新

  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/13/myblog:mysql

   #测试时使用
    ports:
     - 13306:3306

  my-blog:
    image: registry.cn-hangzhou.aliyuncs.com/13/myblog:blog
    ports:
     - 28080:8080
    links:
     - mysql
